package ma.entraide.siipe.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import ma.entraide.siipe.enums.GererPar;
import ma.entraide.siipe.enums.Milieu;
import ma.entraide.siipe.enums.ProprieteType;
import ma.entraide.siipe.enums.TypeLocal;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class EtablissementResponse {
    private Long id;
    private String nomFr;
    private String nomAr;
    private String code;
    private String telephone;
    private String fax;
    private String adresse;
    private Milieu milieu;
    private TypeLocal typeLocal;
    private ProprieteType proprietecentre;
    private GererPar gererPar;
    private String personneResponsableCentre;
    private Double latitude;
    private Double longitude;
    private LocalDate dateConstruction;
    private LocalDate dateExploitation;
    private LocalDate dateAchat;
    private Double superficieTerrain;
    private Double surfaceBatie;
    private Double superficieTotaleEtages;
    private Integer nombreEtage;
    private String etagesUtilises;
    private String composant;
    private Integer capaciteAccueil;
    private String etatConstruction;
    private String observation;
    private String numerotitre;
    private Boolean loyer;
    private Double montantLoyer;
    private String paieLoyer;
    private Boolean raccordementEauPotable;
    private Boolean raccordementElectricite;
    private Boolean planSituation;
    private Boolean planArchitecture;
    private Boolean litige;
    private String raisonsConflit;
    private Double prixBatiment;
    private Boolean autorise;
    private String numeroAutorisation;
    private String utilisation;
    private Long provinceId;
    private String provinceNom;
    private Long regionId;
    private String regionNom;
    private String mappeCadastraleUrl;
    private String certificatProprieteUrl;
    private String planSituationUrl;
    private String planArchitectureUrl;
    private String photoUrl;
    private List<ProgrammeResponse> programmes;
    private LocalDateTime createdAt;
    private String createdBy;
    private LocalDateTime updatedAt;
    private String updatedBy;
    private List<Long> prestationIds;
    private List<PrestationResponse> prestations;
}