package ma.entraide.siipe.enums;

public enum Fonction {
    DIRECTEUR,
    INSPECTEUR,
    SOUS_DIRECTEUR,
    CHEF_DE_DIVISION,
    CHEF_DE_SERVICE,
    DIRECTEUR_REGIONAL,
    DIRECTEUR_PROVINCIAL,
    DIRECTEUR_DU_CENTRE,
    RESPONSABLE_ADMINISTRATIF_FINANCIER,
    AGENT_SURVEILLANCE_SECURITE,
    ASSISTANT_SOCIAL,
    MEDECIN,
    INFIRMIER,
    PSYCHOLOGUE,
    EDUCATEUR,
    FORMATEUR,
    CHEF_BUREAU_ADMINISTRATIF_TECHNIQUE
}
